os: osx
language: rust
osx_image: xcode11.3
rust:
  - stable

cache:
  cargo: true
  directories:
    - $HOME/.cargo

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

notifications:
  email: false

before_install:
  - env
  - locale
  - xcodebuild -version
  - xcodebuild -showsdks
  - rustup target add aarch64-apple-ios armv7-apple-ios armv7s-apple-ios x86_64-apple-ios i386-apple-ios x86_64-apple-darwin
  - rustup update
  - cargo install cargo-lipo
  - cargo install cbindgen
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install nasm

script:
  - set -o pipefail
  - mkdir include
  - rm -rf rav1e
  - git clone -b v0.3.1 --depth 1 https://github.com/xiph/rav1e.git
  - cd rav1e
  - cbindgen -c cbindgen.toml -l C -o include/rav1e/rav1e.h --crate rav1e .
  # macOS
  - cargo build --release --no-default-features --features "asm capi" --target x86_64-apple-darwin
  # iOS
  - cargo lipo --release --no-default-features --features "capi" --targets=aarch64-apple-ios,armv7-apple-ios,x86_64-apple-ios,i386-apple-ios

before_deploy:
  # iOS
  - cd $TRAVIS_BUILD_DIR
  - mkdir Build
  - cd Build
  - mkdir iOS
  - cd iOS
  - mkdir librav1e.framework
  - cd librav1e.framework
  - mkdir Headers
  - mkdir Modules
  - cp $TRAVIS_BUILD_DIR/rav1e/target/universal/release/librav1e.a librav1e
  - cp $TRAVIS_BUILD_DIR/rav1e/include/rav1e/rav1e.h Headers/
  - cp $TRAVIS_BUILD_DIR/module.modulemap Modules/
  # macOS
  - cd $TRAVIS_BUILD_DIR
  - cd Build
  - mkdir Mac
  - cd Mac
  - mkdir librav1e.framework
  - cd librav1e.framework
  - mkdir Versions
  - cd Versions
  - mkdir A
  - ln -s A Current
  - cd A
  - mkdir Headers
  - mkdir Modules
  - cp $TRAVIS_BUILD_DIR/rav1e/target/x86_64-apple-darwin/release/librav1e.a librav1e
  - cp $TRAVIS_BUILD_DIR/rav1e/include/rav1e/rav1e.h Headers/
  - cp $TRAVIS_BUILD_DIR/module.modulemap Modules/
  - cd ../../
  - ln -s Versions/Current/librav1e librav1e
  - ln -s Versions/Current/Headers Headers
  - ln -s Versions/Current/Modules Modules
  # zip
  - cd $TRAVIS_BUILD_DIR
  - cd Build
  - zip -r librav1e.zip Mac/ iOS/

deploy:
  provider: releases
  api_key:
    secure: jPRzCQzncgGtR318Yg0Uv3Q41H1bco2Tk92DhgV+OvYfQvv4cZTMzUmWzWKjp5axYzQo8GeZdlt/ZPk+A6qt8wudZivXCH0LPkjud22rnGYJ3+IElMwf32kCxDjTfnhKEvHBu8UY7HIELjE2Ac//y9eZh40dhVC27Q+j+DRmdbJ5wtzDkrgAyp83ptdHxFdwEJhC8wfVTKSQ/ODwo4WFuRAx15ZoZzgEnrnrYRqQpUOi9qyc+sFN7rtHOdFFIv/IXyQQLpw9GJaR0/KhZbv/u1b18EfCjFNVJSFjHuZvZ6NV4waBn6VpEPtcD7puFud0eLDiMg1zy9Iyfkl/eK1kiTLxZpgBT44ZJWUdyzYtWEZ+b/lw5H08NjSe88Sd08JWQf6YE0c114Wx4jB2Rh7UiLjrRmNg413sseCd/w9IcJJzympm45pcCvGh+PuFGxjjkM+H4H51IbxIKWe6RBma+wFCb5w17Oj9oQ22awBsvUrjFYay7j8N7dGq3TwVJ2w5MVq2969oklZTuJEb0Dya8up9iMLRKa2XSV3kUQD1yqWYPVoLxkiYpprI/ZrRtu2VwKSNGRCIcXQPXZowUrtVvsq2M/q1m34O2DKsLcC9JmoXKchxPwLdZVXK8AH3oces3u3/KEP53P8vgE6hrqXrfJCKGXudigEQyEhKhMuxvpI=
  file: $TRAVIS_BUILD_DIR/Build/librav1e.zip
  skip_cleanup: true
  on:
    tags: true
    repo: SDWebImage/librav1e-Xcode
